image: python:3-alpine

before_script:
  - apk update
  - apk add zip

stages:
  - test
  - build

test:
  stage: test
  script:
    - python -mjson.tool 'tr-TR/tr.json' > /dev/null
    - python -mjson.tool 'tr-TR/module.json' > /dev/null

build:
  stage: build
  script:
    - zip dnd5e-tr-TR.zip -r tr-TR -x ".*"
  artifacts:
    name: dnd5e-tr-TR
    when: on_success
    expire_in: never
    paths:
      - dnd5e-tr-TR.zip
  when: on_success
  only:
    - tags
